# Alphabet Soup Charity

UC Berkeley Extension Data Analytics Boot Camp Module 19 Challenge

---

### Import dependencies

In [15]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.model_selection import train_test_split
import tensorflow as tf

### Import and characterize the input data

In [16]:
file_name = "../Resources/charity_data.csv"
charity_df = pd.read_csv(file_name)
charity_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [17]:
charity_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34299 entries, 0 to 34298
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   EIN                     34299 non-null  int64
 1   NAME                    34299 non-null  object
 2   APPLICATION_TYPE        34299 non-null  object
 3   AFFILIATION             34299 non-null  object
 4   CLASSIFICATION          34299 non-null  object
 5   USE_CASE                34299 non-null  object
 6   ORGANIZATION            34299 non-null  object
 7   STATUS                  34299 non-null  int64
 8   INCOME_AMT              34299 non-null  object
 9   SPECIAL_CONSIDERATIONS  34299 non-null  object
 10  ASK_AMT                 34299 non-null  int64
 11  IS_SUCCESSFUL           34299 non-null  int64
dtypes: int64(4), object(8)
memory usage: 3.1+ MB

In [18]:
# EIN and Name both not needed

charity_df = charity_df.drop(["EIN"], axis=1)
charity_df.head()

,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

### Binning Process

Reducing the number of bins using cutoff values determined by trial and error

In [28]:

names

OTHER                                                28539
PARENT BOOSTER USA INC                                1260
TOPS CLUB INC                                          765
UNITED STATES BOWLING CONGRESS INC                     700
WASHINGTON STATE UNIVERSITY                            492
AMATEUR ATHLETIC UNION OF THE UNITED STATES INC        408
PTA TEXAS CONGRESS                                     368
SOROPTIMIST INTERNATIONAL OF THE AMERICAS INC          331
ALPHA PHI SIGMA                                        313
TOASTMASTERS INTERNATIONAL                             293
MOST WORSHIPFUL STRINGER FREE AND ACCEPTED MASONS      287
LITTLE LEAGUE BASEBALL INC                             277
INTERNATIONAL ASSOCIATION OF LIONS CLUBS               266
Name: NAME, dtype: int64

In [29]:
# check for which names show up multiple times and what threshold we can create an "other" section at
names = charity_df.NAME.value_counts()

replace_names = list(names[names < 250].index)

# Replace values in df with "Other"
for name in replace_names:
    charity_df['NAME'] = charity_df['NAME'].replace(name,'OTHER')

charity_df['NAME'].value_counts()

OTHER                                                28539
PARENT BOOSTER USA INC                                1260
TOPS CLUB INC                                          765
UNITED STATES BOWLING CONGRESS INC                     700
WASHINGTON STATE UNIVERSITY                            492
AMATEUR ATHLETIC UNION OF THE UNITED STATES INC        408
PTA TEXAS CONGRESS                                     368
SOROPTIMIST INTERNATIONAL OF THE AMERICAS INC          331
ALPHA PHI SIGMA                                        313
TOASTMASTERS INTERNATIONAL                             293
MOST WORSHIPFUL STRINGER FREE AND ACCEPTED MASONS      287
LITTLE LEAGUE BASEBALL INC                             277
INTERNATIONAL ASSOCIATION OF LIONS CLUBS               266
Name: NAME, dtype: int64

In [38]:
# determining if number of classifications needs to be reduced
classes = charity_df.CLASSIFICATION.value_counts()

replace_classes = list(classes[classes < 500].index)

for classification in replace_classes:
    charity_df['CLASSIFICATION'] = charity_df['CLASSIFICATION'].replace(classification,'OTHER')

charity_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
OTHER     1484
C7000      777
Name: CLASSIFICATION, dtype: int64

In [41]:
# determining if application types need to be cut down

app_count = charity_df.APPLICATION_TYPE.value_counts()

replace_apps = list(app_count[app_count < 400].index)

for apps in replace_apps:
    charity_df['APPLICATION_TYPE'] = charity_df['APPLICATION_TYPE'].replace(apps,'OTHER')

charity_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
OTHER      276
Name: APPLICATION_TYPE, dtype: int64

### Encoding

In [44]:
# Generate list of columns with categorical variables

cat_vars = charity_df.dtypes[charity_df.dtypes == "object"].index.tolist()

In [45]:
# Create the OneHotEncoder instance (copied from module)

enc = OneHotEncoder(sparse=False)

# Fit and transform the OneHotEncoder using the categorical variable list
encode_df = pd.DataFrame(enc.fit_transform(charity_df[cat_vars]))

# Add the encoded variable names to the DataFrame
encode_df.columns = enc.get_feature_names(cat_vars)
encode_df.head()

,NAME_ALPHA PHI SIGMA,NAME_AMATEUR ATHLETIC UNION OF THE UNITED STATES INC,NAME_INTERNATIONAL ASSOCIATION OF LIONS CLUBS,NAME_LITTLE LEAGUE BASEBALL INC,NAME_MOST WORSHIPFUL STRINGER FREE AND ACCEPTED MASONS,NAME_OTHER,NAME_PARENT BOOSTER USA INC,NAME_PTA TEXAS CONGRESS,NAME_SOROPTIMIST INTERNATIONAL OF THE AMERICAS INC,NAME_TOASTMASTERS INTERNATIONAL,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [46]:
# Merge the datasets and drop the categorical values

charity_df = charity_df.merge(encode_df, left_index = True, right_index = True)
charity_df = charity_df.drop(cat_vars,1)
charity_df.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,NAME_ALPHA PHI SIGMA,NAME_AMATEUR ATHLETIC UNION OF THE UNITED STATES INC,NAME_INTERNATIONAL ASSOCIATION OF LIONS CLUBS,NAME_LITTLE LEAGUE BASEBALL INC,NAME_MOST WORSHIPFUL STRINGER FREE AND ACCEPTED MASONS,NAME_OTHER,NAME_PARENT BOOSTER USA INC,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,1,108590,1,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,1,5000,0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1,6692,1,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,1,142590,1,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

### Split into Testing and Training

In [47]:
# Split on IS_SUCCESSFUL into features and targets

y = charity_df['IS_SUCCESSFUL'].values # target
X = charity_df.drop(['IS_SUCCESSFUL'],axis=1).values # everything but the target is a feature

# Split into training and testing

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [48]:
# Create a StandardScaler instance
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

### NN Model 

##### Read the first line of each cell to identify trial type. If running TRIAL 1, only run the tabs listed as TRIAL 1. Results achieved are summarized in the last cell of the notebook.

In [49]:
# Create the Keras Sequential model - INITIAL TRIAL - 1 layer, relu
nn_model = tf.keras.models.Sequential()

# define parameters
# Add the input and hidden layer 
number_inputs = len(X_train[0])
number_hidden_nodes_1 = 25

nn_model.add(tf.keras.layers.Dense(units=number_hidden_nodes_1, activation="relu", input_dim=number_inputs))

# Add the output layer that uses a probability activation function
nn_model.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

nn_model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense (Dense)                (None, 25)                1450
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 26
=================================================================
Total params: 1,476
Trainable params: 1,476
Non-trainable params: 0
_________________________________________________________________

In [53]:
# TRIAL 2 - 2 layers, relu
number_inputs = len(X_train[0])
number_hidden_nodes_1 =  25
number_hidden_nodes_2 = 10

nn_model = tf.keras.models.Sequential()

# Add first layer to the Sequential model using Keras’ Dense class
nn_model.add(tf.keras.layers.Dense(units = number_hidden_nodes_1, input_dim=number_inputs, activation="relu"))
#nn_model.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="tanh"))

# Second hidden layer
nn_model.add(tf.keras.layers.Dense(units=number_hidden_nodes_2, activation="relu"))


# Add the output layer that uses a probability activation function
nn_model.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the Sequential model
nn_model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_2 (Dense)              (None, 25)                1450
_________________________________________________________________
dense_3 (Dense)              (None, 10)                260
_________________________________________________________________
dense_4 (Dense)              (None, 1)                 11
=================================================================
Total params: 1,721
Trainable params: 1,721
Non-trainable params: 0
_________________________________________________________________

In [57]:
# TRIAL 3 - 2 layers, Relu
number_inputs = len(X_train[0])
number_hidden_nodes_1 =  35
number_hidden_nodes_2 = 10

nn_model = tf.keras.models.Sequential()

# Add first layer to the Sequential model using Keras’ Dense class
nn_model.add(tf.keras.layers.Dense(units=number_hidden_nodes_1, input_dim=number_inputs, activation="relu"))

# Second hidden layer
nn_model.add(tf.keras.layers.Dense(units=number_hidden_nodes_2, activation="relu"))


# Add the output layer that uses a probability activation function
nn_model.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the Sequential model
nn_model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_5 (Dense)              (None, 35)                2030
_________________________________________________________________
dense_6 (Dense)              (None, 10)                360
_________________________________________________________________
dense_7 (Dense)              (None, 1)                 11
=================================================================
Total params: 2,401
Trainable params: 2,401
Non-trainable params: 0
_________________________________________________________________

In [61]:
# TRIAL 3 - 2 layers, Relu
number_inputs = len(X_train[0])
number_hidden_nodes_1 =  25
number_hidden_nodes_2 = 15

nn_model = tf.keras.models.Sequential()

# Add first layer to the Sequential model using Keras’ Dense class
nn_model.add(tf.keras.layers.Dense(units=number_hidden_nodes_1, input_dim=number_inputs, activation="relu"))

# Second hidden layer
nn_model.add(tf.keras.layers.Dense(units=number_hidden_nodes_2, activation="relu"))


# Add the output layer that uses a probability activation function
nn_model.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the Sequential model
nn_model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_8 (Dense)              (None, 25)                1450
_________________________________________________________________
dense_9 (Dense)              (None, 15)                390
_________________________________________________________________
dense_10 (Dense)             (None, 1)                 16
=================================================================
Total params: 1,856
Trainable params: 1,856
Non-trainable params: 0
_________________________________________________________________

In [62]:
# Compile the Sequential model together and customize metrics - RUN FOR ALL TRIALS

nn_model.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [55]:
# Test - TRIALS 1-2 both use 100 epochs

fit_model = nn_model.fit(X_train_scaled, y_train, epochs=100)

Train on 25724 samples
Epoch 1/100
25724/25724 [==============================] - 5s 192us/sample - loss: 0.5488 - accuracy: 0.7229
Epoch 2/100
25724/25724 [==============================] - 3s 123us/sample - loss: 0.5160 - accuracy: 0.7473
Epoch 3/100
25724/25724 [==============================] - 3s 108us/sample - loss: 0.5110 - accuracy: 0.7492
Epoch 4/100
25724/25724 [==============================] - 3s 116us/sample - loss: 0.5083 - accuracy: 0.7519
Epoch 5/100
25724/25724 [==============================] - 3s 108us/sample - loss: 0.5069 - accuracy: 0.7509
Epoch 6/100
25724/25724 [==============================] - 3s 114us/sample - loss: 0.5054 - accuracy: 0.7516
Epoch 7/100
25724/25724 [==============================] - 3s 118us/sample - loss: 0.5043 - accuracy: 0.7513
Epoch 8/100
25724/25724 [==============================] - 3s 126us/sample - loss: 0.5034 - accuracy: 0.7531
Epoch 9/100
25724/25724 [==============================] - 4s 138us/sample - loss: 0.5031 - accuracy: 0.7535
Epoch 10/100
25724/25724 [==============================] - 4s 146us/sample - loss: 0.5023 - accuracy: 0.7551
Epoch 11/100
25724/25724 [==============================] - 3s 118us/sample - loss: 0.5016 - accuracy: 0.7553
Epoch 12/100
25724/25724 [==============================] - 3s 112us/sample - loss: 0.5009 - accuracy: 0.7549
Epoch 13/100
25724/25724 [==============================] - 3s 113us/sample - loss: 0.5002 - accuracy: 0.7544
Epoch 14/100
25724/25724 [==============================] - 3s 109us/sample - loss: 0.5002 - accuracy: 0.7563
Epoch 15/100
25724/25724 [==============================] - 3s 110us/sample - loss: 0.4997 - accuracy: 0.7571
Epoch 16/100
25724/25724 [==============================] - 4s 149us/sample - loss: 0.4994 - accuracy: 0.7560
Epoch 17/100
25724/25724 [==============================] - 3s 127us/sample - loss: 0.4990 - accuracy: 0.7559
Epoch 18/100
25724/25724 [==============================] - 4s 154us/sample - loss: 0.4986 - accuracy: 0.7577
Epoch 19/100
25724/25724 [==============================] - 3s 109us/sample - loss: 0.4979 - accuracy: 0.7563
Epoch 20/100
25724/25724 [==============================] - 4s 155us/sample - loss: 0.4978 - accuracy: 0.7575 - loss: 0.4973 - accu
Epoch 21/100
25724/25724 [==============================] - 3s 116us/sample - loss: 0.4978 - accuracy: 0.7573
Epoch 22/100
25724/25724 [==============================] - 3s 111us/sample - loss: 0.4975 - accuracy: 0.7568
Epoch 23/100
25724/25724 [==============================] - 4s 155us/sample - loss: 0.4977 - accuracy: 0.7569
Epoch 24/100
25724/25724 [==============================] - 4s 145us/sample - loss: 0.4973 - accuracy: 0.7566
Epoch 25/100
25724/25724 [==============================] - 4s 151us/sample - loss: 0.4979 - accuracy: 0.7573
Epoch 26/100
25724/25724 [==============================] - 4s 147us/sample - loss: 0.4967 - accuracy: 0.7575
Epoch 27/100
25724/25724 [==============================] - 3s 128us/sample - loss: 0.4969 - accuracy: 0.7580
Epoch 28/100
25724/25724 [==============================] - 3s 111us/sample - loss: 0.4964 - accuracy: 0.7584
Epoch 29/100
25724/25724 [==============================] - 3s 112us/sample - loss: 0.4968 - accuracy: 0.7574
Epoch 30/100
25724/25724 [==============================] - 3s 125us/sample - loss: 0.4962 - accuracy: 0.7583
Epoch 31/100
25724/25724 [==============================] - 3s 122us/sample - loss: 0.4963 - accuracy: 0.7583
Epoch 32/100
25724/25724 [==============================] - 3s 117us/sample - loss: 0.4960 - accuracy: 0.7583
Epoch 33/100
25724/25724 [==============================] - 3s 108us/sample - loss: 0.4958 - accuracy: 0.7580
Epoch 34/100
25724/25724 [==============================] - 3s 105us/sample - loss: 0.4959 - accuracy: 0.7579
Epoch 35/100
25724/25724 [==============================] - 3s 106us/sample - loss: 0.4954 - accuracy: 0.7586
Epoch 36/100
25724/25724 [==============================] - 3s 110us/sample - loss: 0.4957 - accuracy: 0.7570
Epoch 37/100
25724/25724 [==============================] - 3s 104us/sample - loss: 0.4956 - accuracy: 0.7581
Epoch 38/100
25724/25724 [==============================] - 3s 105us/sample - loss: 0.4950 - accuracy: 0.7594
Epoch 39/100
25724/25724 [==============================] - 3s 128us/sample - loss: 0.4955 - accuracy: 0.7578
Epoch 40/100
25724/25724 [==============================] - 5s 182us/sample - loss: 0.4943 - accuracy: 0.7594
Epoch 41/100
25724/25724 [==============================] - 3s 122us/sample - loss: 0.4949 - accuracy: 0.7584
Epoch 42/100
25724/25724 [==============================] - 4s 148us/sample - loss: 0.4945 - accuracy: 0.7586
Epoch 43/100
25724/25724 [==============================] - 3s 111us/sample - loss: 0.4950 - accuracy: 0.7586
Epoch 44/100
25724/25724 [==============================] - 2s 95us/sample - loss: 0.4947 - accuracy: 0.7588
Epoch 45/100
25724/25724 [==============================] - 5s 198us/sample - loss: 0.4947 - accuracy: 0.7585
Epoch 46/100
25724/25724 [==============================] - 4s 161us/sample - loss: 0.4944 - accuracy: 0.7593
Epoch 47/100
25724/25724 [==============================] - 4s 163us/sample - loss: 0.4944 - accuracy: 0.7584
Epoch 48/100
25724/25724 [==============================] - 4s 136us/sample - loss: 0.4941 - accuracy: 0.7579
Epoch 49/100
25724/25724 [==============================] - 3s 125us/sample - loss: 0.4939 - accuracy: 0.7601
Epoch 50/100
25724/25724 [==============================] - 3s 117us/sample - loss: 0.4942 - accuracy: 0.7606
Epoch 51/100
25724/25724 [==============================] - 3s 117us/sample - loss: 0.4938 - accuracy: 0.7591
Epoch 52/100
25724/25724 [==============================] - 3s 117us/sample - loss: 0.4941 - accuracy: 0.7591
Epoch 53/100
25724/25724 [==============================] - 3s 132us/sample - loss: 0.4938 - accuracy: 0.7596
Epoch 54/100
25724/25724 [==============================] - 4s 137us/sample - loss: 0.4935 - accuracy: 0.7599
Epoch 55/100
25724/25724 [==============================] - 3s 120us/sample - loss: 0.4937 - accuracy: 0.7597
Epoch 56/100
25724/25724 [==============================] - 3s 126us/sample - loss: 0.4936 - accuracy: 0.7593
Epoch 57/100
25724/25724 [==============================] - 4s 142us/sample - loss: 0.4932 - accuracy: 0.7602
Epoch 58/100
25724/25724 [==============================] - 4s 167us/sample - loss: 0.4933 - accuracy: 0.7597
Epoch 59/100
25724/25724 [==============================] - 3s 125us/sample - loss: 0.4935 - accuracy: 0.7607
Epoch 60/100
25724/25724 [==============================] - 3s 113us/sample - loss: 0.4932 - accuracy: 0.7593
Epoch 61/100
25724/25724 [==============================] - 3s 115us/sample - loss: 0.4930 - accuracy: 0.7607
Epoch 62/100
25724/25724 [==============================] - 3s 127us/sample - loss: 0.4931 - accuracy: 0.7609
Epoch 63/100
25724/25724 [==============================] - 3s 114us/sample - loss: 0.4933 - accuracy: 0.7598
Epoch 64/100
25724/25724 [==============================] - 3s 111us/sample - loss: 0.4933 - accuracy: 0.7593 - loss: 0.4938 - accuracy: 0.
Epoch 65/100
25724/25724 [==============================] - 3s 118us/sample - loss: 0.4929 - accuracy: 0.7592
Epoch 66/100
25724/25724 [==============================] - 3s 125us/sample - loss: 0.4928 - accuracy: 0.7604
Epoch 67/100
25724/25724 [==============================] - 3s 118us/sample - loss: 0.4929 - accuracy: 0.7596
Epoch 68/100
25724/25724 [==============================] - 3s 116us/sample - loss: 0.4929 - accuracy: 0.7597
Epoch 69/100
25724/25724 [==============================] - 3s 115us/sample - loss: 0.4929 - accuracy: 0.7598
Epoch 70/100
25724/25724 [==============================] - 4s 167us/sample - loss: 0.4928 - accuracy: 0.7603
Epoch 71/100
25724/25724 [==============================] - 4s 140us/sample - loss: 0.4925 - accuracy: 0.7593
Epoch 72/100
25724/25724 [==============================] - 3s 126us/sample - loss: 0.4930 - accuracy: 0.7606
Epoch 73/100
25724/25724 [==============================] - 4s 148us/sample - loss: 0.4929 - accuracy: 0.7605
Epoch 74/100

25724/25724 [==============================] - 4s 141us/sample - loss: 0.4926 - accuracy: 0.7596
Epoch 75/100
25724/25724 [==============================] - 4s 152us/sample - loss: 0.4926 - accuracy: 0.7607
Epoch 76/100
25724/25724 [==============================] - 3s 135us/sample - loss: 0.4927 - accuracy: 0.7610
Epoch 77/100
25724/25724 [==============================] - 3s 115us/sample - loss: 0.4923 - accuracy: 0.7606
Epoch 78/100
25724/25724 [==============================] - 3s 124us/sample - loss: 0.4927 - accuracy: 0.7598
Epoch 79/100
25724/25724 [==============================] - 3s 116us/sample - loss: 0.4923 - accuracy: 0.7602
Epoch 80/100
25724/25724 [==============================] - 3s 110us/sample - loss: 0.4924 - accuracy: 0.7613
Epoch 81/100
25724/25724 [==============================] - 3s 121us/sample - loss: 0.4922 - accuracy: 0.7601
Epoch 82/100
25724/25724 [==============================] - 3s 131us/sample - loss: 0.4922 - accuracy: 0.7610
Epoch 83/100
25724/25724 [==============================] - 3s 126us/sample - loss: 0.4922 - accuracy: 0.7603
Epoch 84/100
25724/25724 [==============================] - 4s 149us/sample - loss: 0.4919 - accuracy: 0.7608
Epoch 85/100
25724/25724 [==============================] - 3s 106us/sample - loss: 0.4921 - accuracy: 0.7609
Epoch 86/100
25724/25724 [==============================] - 3s 124us/sample - loss: 0.4921 - accuracy: 0.7612
Epoch 87/100
25724/25724 [==============================] - 4s 173us/sample - loss: 0.4919 - accuracy: 0.7601
Epoch 88/100
25724/25724 [==============================] - 3s 115us/sample - loss: 0.4921 - accuracy: 0.7607
Epoch 89/100
25724/25724 [==============================] - 3s 123us/sample - loss: 0.4915 - accuracy: 0.7613
Epoch 90/100
25724/25724 [==============================] - 3s 131us/sample - loss: 0.4919 - accuracy: 0.7603
Epoch 91/100
25724/25724 [==============================] - 4s 143us/sample - loss: 0.4922 - accuracy: 0.7609
Epoch 92/100
25724/25724 [==============================] - 4s 141us/sample - loss: 0.4914 - accuracy: 0.7607
Epoch 93/100
25724/25724 [==============================] - 3s 136us/sample - loss: 0.4917 - accuracy: 0.7607
Epoch 94/100
25724/25724 [==============================] - 3s 132us/sample - loss: 0.4918 - accuracy: 0.7606
Epoch 95/100
25724/25724 [==============================] - 3s 123us/sample - loss: 0.4917 - accuracy: 0.7608
Epoch 96/100
25724/25724 [==============================] - 3s 124us/sample - loss: 0.4917 - accuracy: 0.7608
Epoch 97/100
25724/25724 [==============================] - 3s 130us/sample - loss: 0.4914 - accuracy: 0.7611
Epoch 98/100
25724/25724 [==============================] - 5s 177us/sample - loss: 0.4918 - accuracy: 0.7606
Epoch 99/100
25724/25724 [==============================] - 4s 142us/sample - loss: 0.4914 - accuracy: 0.7603
Epoch 100/100
25724/25724 [==============================] - 4s 144us/sample - loss: 0.4914 - accuracy: 0.7612

In [63]:
# Test - TRIALS 3 & 4 use 75 epochs to reduce computation time

fit_model = nn_model.fit(X_train_scaled, y_train, epochs=75)

Train on 25724 samples
Epoch 1/75
25724/25724 [==============================] - 5s 183us/sample - loss: 0.5545 - accuracy: 0.7116
Epoch 2/75
25724/25724 [==============================] - 3s 111us/sample - loss: 0.5129 - accuracy: 0.7499
Epoch 3/75
25724/25724 [==============================] - 3s 117us/sample - loss: 0.5087 - accuracy: 0.7505
Epoch 4/75
25724/25724 [==============================] - 3s 133us/sample - loss: 0.5063 - accuracy: 0.7512
Epoch 5/75
25724/25724 [==============================] - 3s 118us/sample - loss: 0.5043 - accuracy: 0.7521
Epoch 6/75
25724/25724 [==============================] - 3s 129us/sample - loss: 0.5037 - accuracy: 0.7529
Epoch 7/75
25724/25724 [==============================] - 3s 129us/sample - loss: 0.5027 - accuracy: 0.7538
Epoch 8/75
25724/25724 [==============================] - 3s 128us/sample - loss: 0.5013 - accuracy: 0.7556
Epoch 9/75
25724/25724 [==============================] - 3s 114us/sample - loss: 0.5011 - accuracy: 0.7544
Epoch 10/75
25724/25724 [==============================] - 3s 108us/sample - loss: 0.5010 - accuracy: 0.7544
Epoch 11/75
25724/25724 [==============================] - 3s 103us/sample - loss: 0.4997 - accuracy: 0.7549
Epoch 12/75
25724/25724 [==============================] - ETA: 0s - loss: 0.4994 - accuracy: 0.75 - 3s 116us/sample - loss: 0.4995 - accuracy: 0.7558
Epoch 13/75
25724/25724 [==============================] - 3s 134us/sample - loss: 0.4986 - accuracy: 0.7554
Epoch 14/75
25724/25724 [==============================] - 3s 114us/sample - loss: 0.4985 - accuracy: 0.7561
Epoch 15/75
25724/25724 [==============================] - 3s 107us/sample - loss: 0.4986 - accuracy: 0.7569
Epoch 16/75
25724/25724 [==============================] - 3s 103us/sample - loss: 0.4979 - accuracy: 0.7563
Epoch 17/75
25724/25724 [==============================] - 3s 118us/sample - loss: 0.4978 - accuracy: 0.7565
Epoch 18/75
25724/25724 [==============================] - 4s 164us/sample - loss: 0.4972 - accuracy: 0.7584
Epoch 19/75
25724/25724 [==============================] - 4s 145us/sample - loss: 0.4973 - accuracy: 0.7572
Epoch 20/75
25724/25724 [==============================] - 5s 206us/sample - loss: 0.4972 - accuracy: 0.7564
Epoch 21/75
25724/25724 [==============================] - 6s 235us/sample - loss: 0.4965 - accuracy: 0.7571
Epoch 22/75
25724/25724 [==============================] - 5s 200us/sample - loss: 0.4966 - accuracy: 0.7576
Epoch 23/75
25724/25724 [==============================] - 4s 163us/sample - loss: 0.4965 - accuracy: 0.7578
Epoch 24/75
25724/25724 [==============================] - 3s 120us/sample - loss: 0.4964 - accuracy: 0.7571
Epoch 25/75
25724/25724 [==============================] - 3s 118us/sample - loss: 0.4959 - accuracy: 0.7575
Epoch 26/75
25724/25724 [==============================] - 3s 123us/sample - loss: 0.4959 - accuracy: 0.7574
Epoch 27/75
25724/25724 [==============================] - 3s 125us/sample - loss: 0.4956 - accuracy: 0.7573
Epoch 28/75
25724/25724 [==============================] - 3s 122us/sample - loss: 0.4957 - accuracy: 0.7582
Epoch 29/75
25724/25724 [==============================] - 3s 118us/sample - loss: 0.4949 - accuracy: 0.7588
Epoch 30/75
25724/25724 [==============================] - 3s 119us/sample - loss: 0.4953 - accuracy: 0.7577
Epoch 31/75
25724/25724 [==============================] - 3s 127us/sample - loss: 0.4951 - accuracy: 0.7582
Epoch 32/75
25724/25724 [==============================] - 3s 120us/sample - loss: 0.4947 - accuracy: 0.7579
Epoch 33/75
25724/25724 [==============================] - 3s 121us/sample - loss: 0.4945 - accuracy: 0.7589
Epoch 34/75
25724/25724 [==============================] - 3s 132us/sample - loss: 0.4948 - accuracy: 0.7597
Epoch 35/75
25724/25724 [==============================] - 3s 119us/sample - loss: 0.4945 - accuracy: 0.7586
Epoch 36/75
25724/25724 [==============================] - 3s 130us/sample - loss: 0.4944 - accuracy: 0.7593
Epoch 37/75
25724/25724 [==============================] - 3s 121us/sample - loss: 0.4944 - accuracy: 0.7582
Epoch 38/75
25724/25724 [==============================] - 4s 149us/sample - loss: 0.4942 - accuracy: 0.7607
Epoch 39/75
25724/25724 [==============================] - 3s 124us/sample - loss: 0.4936 - accuracy: 0.7593
Epoch 40/75
25724/25724 [==============================] - 3s 115us/sample - loss: 0.4940 - accuracy: 0.7587
Epoch 41/75
25724/25724 [==============================] - 3s 124us/sample - loss: 0.4936 - accuracy: 0.7586
Epoch 42/75
25724/25724 [==============================] - 4s 148us/sample - loss: 0.4942 - accuracy: 0.7589
Epoch 43/75
25724/25724 [==============================] - 6s 219us/sample - loss: 0.4934 - accuracy: 0.7589
Epoch 44/75
25724/25724 [==============================] - 5s 180us/sample - loss: 0.4931 - accuracy: 0.7583
Epoch 45/75
25724/25724 [==============================] - 3s 134us/sample - loss: 0.4932 - accuracy: 0.7591
Epoch 46/75
25724/25724 [==============================] - 6s 216us/sample - loss: 0.4930 - accuracy: 0.7587
Epoch 47/75
25724/25724 [==============================] - 4s 138us/sample - loss: 0.4934 - accuracy: 0.7591
Epoch 48/75
25724/25724 [==============================] - 3s 127us/sample - loss: 0.4934 - accuracy: 0.7598
Epoch 49/75
25724/25724 [==============================] - 3s 128us/sample - loss: 0.4929 - accuracy: 0.7601
Epoch 50/75
25724/25724 [==============================] - 3s 118us/sample - loss: 0.4932 - accuracy: 0.7602 - loss: 0.4914 -
Epoch 51/75
25724/25724 [==============================] - 3s 135us/sample - loss: 0.4930 - accuracy: 0.7596
Epoch 52/75
25724/25724 [==============================] - 3s 121us/sample - loss: 0.4928 - accuracy: 0.7591
Epoch 53/75
25724/25724 [==============================] - 3s 115us/sample - loss: 0.4933 - accuracy: 0.7597
Epoch 54/75
25724/25724 [==============================] - 3s 114us/sample - loss: 0.4928 - accuracy: 0.7595
Epoch 55/75
25724/25724 [==============================] - 3s 113us/sample - loss: 0.4928 - accuracy: 0.7595
Epoch 56/75
25724/25724 [==============================] - 3s 114us/sample - loss: 0.4926 - accuracy: 0.7593
Epoch 57/75
25724/25724 [==============================] - 3s 114us/sample - loss: 0.4922 - accuracy: 0.7607
Epoch 58/75
25724/25724 [==============================] - 3s 118us/sample - loss: 0.4927 - accuracy: 0.7591 - loss: 0.4927 - accuracy:
Epoch 59/75
25724/25724 [==============================] - 5s 184us/sample - loss: 0.4924 - accuracy: 0.7601
Epoch 60/75
25724/25724 [==============================] - 4s 143us/sample - loss: 0.4924 - accuracy: 0.7589
Epoch 61/75
25724/25724 [==============================] - 3s 114us/sample - loss: 0.4923 - accuracy: 0.7601
Epoch 62/75
25724/25724 [==============================] - 3s 135us/sample - loss: 0.4920 - accuracy: 0.7602
Epoch 63/75
25724/25724 [==============================] - 3s 121us/sample - loss: 0.4920 - accuracy: 0.7608
Epoch 64/75
25724/25724 [==============================] - 3s 119us/sample - loss: 0.4920 - accuracy: 0.7603 - los
Epoch 65/75
25724/25724 [==============================] - 3s 124us/sample - loss: 0.4921 - accuracy: 0.7602
Epoch 66/75
25724/25724 [==============================] - 3s 117us/sample - loss: 0.4918 - accuracy: 0.7608
Epoch 67/75
25724/25724 [==============================] - 3s 118us/sample - loss: 0.4916 - accuracy: 0.7608
Epoch 68/75
25724/25724 [==============================] - 3s 119us/sample - loss: 0.4923 - accuracy: 0.7603
Epoch 69/75
25724/25724 [==============================] - 3s 125us/sample - loss: 0.4914 - accuracy: 0.7600
Epoch 70/75
25724/25724 [==============================] - 3s 124us/sample - loss: 0.4915 - accuracy: 0.7612
Epoch 71/75
25724/25724 [==============================] - 3s 124us/sample - loss: 0.4915 - accuracy: 0.7601
Epoch 72/75
25724/25724 [==============================] - 3s 124us/sample - loss: 0.4915 - accuracy: 0.7602
Epoch 73/75
25724/25724 [==============================] - 3s 131us/sample - loss: 0.4917 - accuracy: 0.7615
Epoch 74/75
25724/25724 [==============================] - 3s 122us/sample - loss: 0.4917 - accuracy: 0.7606
Epoch 75/75

25724/25724 [==============================] - 3s 119us/sample - loss: 0.4915 - accuracy: 0.7605

In [52]:
# Evaluate model performance using the test data - TRIAL 1
model_loss, model_accuracy = nn_model.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

8575/1 - 1s - loss: 0.4747 - accuracy: 0.7450
Loss: 0.5097151760839512, Accuracy: 0.7449562549591064

In [56]:
# Evaluate model performance using the test data - TRIAL 2
model_loss, model_accuracy = nn_model.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

8575/1 - 1s - loss: 0.4712 - accuracy: 0.7493
Loss: 0.5084301748185394, Accuracy: 0.7492711544036865

In [60]:
# Evaluate model performance using the test data - TRIAL 3
model_loss, model_accuracy = nn_model.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

8575/1 - 1s - loss: 0.4695 - accuracy: 0.7487
Loss: 0.5076871745231896, Accuracy: 0.7486880421638489

In [64]:
# Evaluate model performance using the test data - TRIAL 4
model_loss, model_accuracy = nn_model.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

8575/1 - 1s - loss: 0.4738 - accuracy: 0.7468
Loss: 0.5111516482454694, Accuracy: 0.7468221783638

### Notes on combinations tried:
    
Trial 1: 1 layer, 25 nodes, Relu, 100 epochs -- ACCURACY SCORE: 74.5% - Very close to our goal of 75%.

- Our initial model performed very close to our target accuracy of 75%

Trial 2: 2 layer, 25/10 nodes, Relu, 100 epochs -- ACCURACY SCORE: 74.9% - Even closer to 75%!

- Adding a second layer to our model slightly increased our accuracy.

Trial 3: 1 layer, 35/10 nodes, Relu, 75 epochs -- ACCURACY SCORE: 74.8 % - Slight degradation over Trial 2.

- We reduced the number of epochs since there was not much of an improvement in loss or accuracy beyond 60-75 epochs. We found that increasing the number of nodes in layer 1 did not improve our accuracy.

Trial 4: 1 layer, 25/15 nodes, Relu, 75 epochs -- ACCURACY SCORE: 74.7% - Slight degradation over Trial 3.

- In this trial, we reduced the number of layer 1 nodes back to 25, and increased the number of layer 2 nodes to 15. We found that this model performed worse than our second attempt. However, all four attempts were within 1 percentage point of our target accuracy of 75%.